import type { InstanceStatus, MetricSample } from "./types";

const baseTime = Date.now();
const metrics: MetricSample[] = Array.from({ length: 28 }, (_, index) => ({
  at: new Date(baseTime - (27 - index) * 60_000).toISOString(),
  nodeRssMb: 67 + (index % 4) * 0.6,
  nodeHeapMb: 31 + (index % 5) * 0.4,
  chromiumRssMb: 278 + Math.sin(index / 2) * 7 + (index % 3),
  chromiumCpuPercent: 1.2 + ((index * 7) % 10) / 10,
  jsHeapMb: 74 + (index % 6) * 0.8,
  domNodes: 3860 + index * 2,
  websocketCount: 1,
}));

const healthyObservation = {
  contractComplete: true,
  gameReady: true,
  loginRequired: false,
  characterPresent: true,
  characterFainted: false,
  hpPercent: 82,
  huntActive: true,
  suppliesMissing: false,
  autoPotionEnabled: true,
  autoReviveEnabled: true,
  connected: true,
};

export const demoInstances: InstanceStatus[] = [
  {
    id: "principal",
    accountLabel: "treinador•••",
    environment: "local",
    state: "MONITOR_COMBAT",
    tone: "healthy",
    running: true,
    pid: 14024,
    startedAt: new Date(baseTime - 67_320_000).toISOString(),
    lastHeartbeat: new Date(baseTime).toISOString(),
    reason: null,
    restartCount: 0,
    circuitOpenUntil: null,
    observation: healthyObservation,
    latestMetric: metrics.at(-1) ?? null,
    metrics,
  },
  {
    id: "alt-lab",
    accountLabel: "laboratório•••",
    environment: "local",
    state: "SAFE_STOP",
    tone: "stopped",
    running: false,
    pid: null,
    startedAt: null,
    lastHeartbeat: new Date(baseTime - 720_000).toISOString(),
    reason: "Parada solicitada pelo operador",
    restartCount: 0,
    circuitOpenUntil: null,
    observation: null,
    latestMetric: null,
    metrics: [],
  },
  {
    id: "vps-02",
    accountLabel: "conta-remota•••",
    environment: "VPS",
    state: "LOGIN_REQUIRED",
    tone: "attention",
    running: true,
    pid: 984,
    startedAt: new Date(baseTime - 1_860_000).toISOString(),
    lastHeartbeat: new Date(baseTime - 180_000).toISOString(),
    reason: "Login manual necessário",
    restartCount: 1,
    circuitOpenUntil: null,
    observation: { ...healthyObservation, gameReady: false, loginRequired: true, huntActive: false },
    latestMetric: null,
    metrics: [],
  },
];
